from typing import TYPE_CHECKING, Any, Dict, Iterator, List, Optional, Tuple, Union

if TYPE_CHECKING:
    import pyarrow as pa

CLOSED: str
READ_ONLY: str
READ_WRITE: str
IN_MEMORY: str
ON_DISK: str

class TableStatus:
    Closed: "TableStatus"
    ReadOnly: "TableStatus"
    ReadWrite: "TableStatus"

class TableLocation:
    InMemory: "TableLocation"
    OnDisk: "TableLocation"

class FastDbfError(Exception): ...
class DbfFormatError(FastDbfError): ...
class UnsupportedDbfTypeError(FastDbfError): ...

class Record:
    def __len__(self) -> int: ...
    def __getitem__(self, key: Union[int, str]) -> Any: ...
    def __setitem__(self, key: Union[int, str], value: Any) -> None: ...
    def __iter__(self) -> Iterator[Any]: ...
    def __enter__(self) -> "Record": ...
    def __exit__(self, exc_type: Any, exc_value: Any, traceback: Any) -> None: ...
    def get(self, key: str, default: Any = None) -> Any: ...
    def keys(self) -> List[str]: ...
    def values(self) -> List[Any]: ...
    def items(self) -> List[Tuple[str, Any]]: ...

class Table:
    def __init__(
        self,
        filename: str,
        field_specs: Optional[str] = None,
        dbf_type: Optional[str] = None,
        codepage: Optional[str] = None,
    ) -> None: ...
    def open(self, mode: str = "r") -> "Table": ...
    def close(self) -> None: ...
    def __enter__(self) -> "Table": ...
    def __exit__(self, exc_type: Any, exc_value: Any, traceback: Any) -> None: ...
    def __iter__(self) -> Iterator[Record]: ...
    def __next__(self) -> Record: ...
    def __len__(self) -> int: ...
    def __getitem__(self, index: int) -> Record: ...
    def append(self, row: Union[Dict[str, Any], List[Any], Tuple[Any, ...]]) -> None: ...
    def fields(self) -> List[Dict[str, Any]]: ...
    def row(self, index: int) -> Record: ...
    def records(self) -> List[Dict[str, Any]]: ...
    def to_columns(self) -> Dict[str, List[Any]]: ...
    def extend_columns(self, columns: Dict[str, List[Any]]) -> None: ...
    def to_arrow(self) -> "pa.RecordBatch": ...
    def extend_arrow(self, batch: "pa.RecordBatch") -> None: ...
    def new(
        self,
        filename: str = ":memory:",
        field_specs: Optional[str] = None,
        dbf_type: Optional[str] = None,
    ) -> "Table": ...
    @property
    def field_names(self) -> List[str]: ...
    @property
    def record_count(self) -> int: ...
    @property
    def kind(self) -> str: ...
    @property
    def status(self) -> TableStatus: ...
    @property
    def location(self) -> TableLocation: ...
    @property
    def filename(self) -> Optional[str]: ...
